header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CMakePP

  paths-ignore:
    - .github/worklflows/*
    - cminx/parser/
    - docs/source/.templates
    - docs/source/developer/uml_diagrams/*.drawio
    - docs/Makefile
    - tests/.coveragerc
    - CODE_OF_CONDUCT.md
    - LICENSE
    - version.txt


  comment: never
