header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CMakePP Team
  paths:
    - cmake
    - cminx
    - docs
    - tests
  paths-ignore:
    - "__pycache__"
    - "parser"
    - "build"
    - ".templates"
    - "virt_env"


  comment: on-failure
