if(PACKAGE_FIND_NAME STREQUAL "CMinx")

	if(PACKAGE_FIND_VERSION STREQUAL "@CMINX_VERSION@")
		set(PACKAGE_VERSION_EXACT TRUE)
		set(PACKAGE_VERSION_COMPATIBLE TRUE)
	endif()
	set(PACKAGE_VERSION "@CMINX_VERSION@")

endif()
