name: Add Licenses

on:
  pull_request:
    branches:
      - master

jobs:
  license-eye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Apply Licenses
        uses: apache/skywalking-eyes@main
        with:
          config: .github/.licenserc.yaml
          mode: fix
      - name: Push Licensed Files
        uses: EndBug/add-and-commit@v4
        with:
          author_name: github_actions
          author_email: robot@example.com
          message: 'Committing license headers'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
