name: Add Licenses

on:
  pull_request:
    branches:
      - master

jobs:
  license-eye:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2
      - name: Run License-Eye
        uses: ryanmrichard/skywalking-eyes@add_cmake_support
        with:
          config: .github/.licenserc.yaml
          mode: fix
      - name: Commit Changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          push: false
          pull: 'NO-PULL'
      - name: Check
        run: echo "Committed ${{ steps.Commit-Changes.output.committed }}"
