
# Copyright 2022 CMakePP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: Format Python Source

on:
  pull_request:
    branches:
      - master
jobs:
  format_python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Apply autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --recursive
                --in-place
                --aggressive
                --aggressive
                --exclude cminx/parser
                cminx/

      - name: Push formated source
        uses: EndBug/add-and-commit@v4
        with:
          author_name: ryanmrichard
          author_email: cmakepp[bot]@github.com
          message: "apply autopep8 [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
