name: Apply Apache 2.0 License

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: apache/skywalking-eyes@v0.2.0
        with:
          config: .github/.licenserc.yaml
